name: My First Action

on:
  push:

jobs:
  lint-test-build:
    runs-on: ubuntu-latest

    steps:
      - name: Shri Ganesha
        run: echo "Shri Ganesha"

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: '17'

      - name: Lint
        run: mvn checkstyle:check

      - name: Test
        run: mvn test

      - name: Build
        run: mvn clean package
